### ISSUE TITLE
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void 

### ISSUE THREAD

**Issue by algoteam5** [Jingkang50/ICCV21_SCOOD#3]
```
Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:265; details: cublas failed (13): (512, 256) x (1000, 256)' = (512, 1000) gemm params m 1000 n 512 k 256 trA T trB N lda 256 ldb 256 ldc 1000
[1]    135532 abort (core dumped)  python train.py --config configs/train/cifar10_udg.yml --data_dir data  
```
I got this error which cost me a ton of time to fix but still failed. I am using cuda 11.4, torch=1.8, 4 A
100 GPUs

**Comment by Jingkang50** [comment]
Sorry to hear that... Actually I did not meet this error before. 
Our recommended environment is [here](https://github.com/Jingkang50/SCOOD/blob/master/environment.yml). Maybe try to build exactly with this environment?
I know some of our users successfully run our code on their GTX1080, RTX3070, and Telsa V-100 (but I dont know whether A100 is the problem, usually not).
Good luck!

**Comment by algoteam5** [comment]
Thank you for the answer. This error originates from faiss library which relates to C++ cuda stuff which i dont really know how to fix :D.

**Comment by algoteam5** [comment]
Btw, do you think that by changing these parameters can resolve the issue?:
- labeled_batch_size: 128
- unlabeled_batch_size: 256
- num_clusters: 1000
- test_batch_size: 200

Because in the error it says something about the dim
`(512, 256) x (1000, 256)' = (512, 1000) gemm params m 1000 n 512 k 256 trA T trB N lda 256 ldb 256 ldc 1000`

**Comment by Jingkang50** [comment]
I kinda believe it's still the environment issue, as we find [the similar issue](https://github.com/facebookresearch/faiss/issues/1405) is reported in original faiss repo. What I could suggest is to follow the exact configuration as we provided [here](https://github.com/Jingkang50/SCOOD/blob/master/environment.yml), hope it works.

Good luck!

**Comment by kapilw25** [comment]
> Sorry to hear that... Actually I did not meet this error before. Our recommended environment is [here](https://github.com/Jingkang50/SCOOD/blob/master/environment.yml). Maybe try to build exactly with this environment? I know some of our users successfully run our code on their GTX1080, RTX3070, and Telsa V-100 (but I dont know whether A100 is the problem, usually not). Good luck!

https://github.com/Jingkang50/SCOOD/blob/master/environment.yml
it is giving error
