### ISSUE TITLE
The volatility of reproducibility results

### ISSUE THREAD

**Issue by LuFan31** [Jingkang50/ICCV21_SCOOD#6]
Thank you for your great job!  I've run your code many times(with idf method of ‘udg’ ),but the results have been fluctuating. Your results in Github are expressed by means and standard ,do you think the  volatility comes from the randomness of Clustering used in your paper？

**Comment by Jingkang50** [comment]
Thank you for your question.
Basically yes, the quality of clustering can affect IDF part.
Also, it is an end-to-end model, so the clustering quality may not be guaranteed in the first few epochs, and the error may accumulate. However, the method still converges and works, means that the clustering works but may not be stable. We believe the method can have a better and stable result with pretrained model.

**Comment by LuFan31** [comment]
I got it.Thanks for your answer!
