### ISSUE TITLE
the "sc_label" in train_tin.txt for benchmark cifar100

### ISSUE THREAD

**Issue by ZhimaoPeng** [Jingkang50/ICCV21_SCOOD#7]
Thank you for your great job! 

We find that the "sc_label" in train_tin.txt for benchmark cifar100 are all "-1", according to my understanding, "sc_label" represents the gt label of the sample corresponding to CIFAR100 data set. Do you think this needs to be modified?

**Comment by Jingkang50** [comment]
Thank you for your interests in our work. 
Generally I used `sc_label` to simply mark whether a sample factually belongs to CIFAR 100. If not, these samples could be assigned to some class or OOD during UDG process. So `sc_label` is not necessarily GT, and I don't think we manually annotated CIFAR-100 classes for TinyImageNet training set.

Hope it helps.

**Comment by ZhimaoPeng** [comment]
> Thank you for your interests in our work. Generally I used `sc_label` to simply mark whether a sample factually belongs to CIFAR 100. If not, these samples could be assigned to some class or OOD during UDG process. So `sc_label` is not necessarily GT, and I don't think we manually annotated CIFAR-100 classes for TinyImageNet training set.
> 
> Hope it helps.

this is some annotation information stored in “train_tin.txt” for benchmark cifar10：
![label_info](https://github.com/Jingkang50/ICCV21_SCOOD/assets/37007544/dedb81df-690b-46d5-8eec-92e0fb55d1b6)

this is some annotation information stored in “train_tin.txt” for benchmark cifar100：
![label_info_cifar100](https://github.com/Jingkang50/ICCV21_SCOOD/assets/37007544/b69e1321-7fb0-4d65-adde-6b8c5993d853)


This difference confuses me, so let me assume that you provide class annotations for CIFAR100 for the TinyImageNet training set.

**Comment by Jingkang50** [comment]
Yes, I remember we annotated TIN training with CIFAR-10 labels for detailed analysis and ablation studies, but might not do the same annotation for cifar100 training (if I remember it correctly). So maybe just ignore sc_label for CIFAR-100 if they are all -1.

**Comment by ZhimaoPeng** [comment]
> Yes, I remember we annotated TIN training with CIFAR-10 labels for detailed analysis and ablation studies, but might not do the same annotation for cifar100 training (if I remember it correctly). So maybe just ignore sc_label for CIFAR-100 if they are all -1.

Yes, these labels are mainly to help analyze the experimental results, thank you for your quick reply!
